#!/bin/ba${cWH}S${cC}h

. /home/back/.scripts/Booeysays_logo/colors.sh



clear
echo ""
echo ""
echo ""
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}        "
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}        "
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}     ${cWH}S${cC}     ${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}     ${cWH}S${cC}     ${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cR}#${cC}${cR}#${cC}${cW}+${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cR}#${cC}${cR}#${cC}${cW}+${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}  	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cW}+${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}	 ( HTTPS://BOOEYSAYS.COM )	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}+${cC}${cW}+${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}						"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}                    ..... get it ?"
echo ""
echo ""
echo ""
. /home/back/.scripts/Booeysays_logo/unset_colors.sh
