#!/bin/ba${cWH}S${cC}h

. colors.sh




echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}        "
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}     ${cWH}S${cC}     ${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	                                     ${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}  ${cWH}S${cC}${cWH}S${cC}     ${cWH}S${cC}     ${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC} ${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cW}O${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cW}O${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}E${cC}${cW}E${cC}${cW}E${cC}${cB}X${cC}${cB}X${cC}${cW} ${cC}${cR}#${cC}${cR}#${cC}${cW} ${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC} 	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cW}E${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}E${cC}${cB}X${cC}${cW} ${cC}${cR}#${cC}${cR}#${cC}${cW} ${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cW}E${cC}${cW}E${cC}${cW}E${cC}${cW}E${cC}${cW}E${cC}${cB}X${cC}${cB}X${cC}${cW} ${cC}${cW} ${cC}${cW} ${cC}${cR}#${cC}${cR}#${cC}${cWH}S${cC}${cWH}S${cC}${cWH}S${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}  	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cW}E${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cR}#${cC}${cR}#${cC}${cW} ${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}${cR}#${cC}	"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cB}X${cC}${cW}E${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}E${cC}${cB}X${cC}${cW} ${cC}${cB}X${cC}${cB}X${cC}${cW} ${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}						"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cW}B${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cW}O${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}O${cC}${cW}O${cC}${cW}O${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW}E${cC}${cW}E${cC}${cW}E${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cW} ${cC}${cW} ${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}						"
echo -e "	    ${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}${cB}X${cC}						"

. unset_colors.sh
